package com.exception.day01;

public class Demo4 {
	public static void main(String[] args) {
		try {
			
		} catch (Exception e) {
			// TODO: handle exception
		} finally {
			//finaly里的代码一定会执行，无论try里面有没有出现异常
		}
	}
}
